# Generated by Django 3.1.5 on 2021-02-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLearningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to='')),
                ('transformations', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Inference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deeplearningmodel')),
            ],
        ),
    ]
